### ISSUE TITLE
Get current user

### ISSUE THREAD

**Issue by aguss787** [aguss787/cs2102#15]
getCurrentUser():
- get current logged user object

**Comment by ocayosafat** [comment]
so if the user is taker, Can I get $user->preference or $user->one_star  ??
// $user->getCurrentUser();

**Comment by ocayosafat** [comment]
or is it still the same getTaker(), then $taker->one_star

**Comment by aguss787** [comment]
@ocayosafat No, you have to use the taker class

**Comment by aguss787** [comment]
SignIn now will set email in session
